[tool.black]
skip-string-normalization = true

[tool.pytest.ini_options]
testpaths = ["mpl_uncertainties/tests"]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mpl-uncertainties"
dynamic = ["version"]
readme = "README.md"
dependencies = ["uncertainties>=3.2.3,<4.0.0", "matplotlib"]

[dependency-groups]
tests = ["pytest", "pytest-mpl"]
docs = ["sphinx", "sphinx_copybutton", "sphinx_gallery", "numpydoc", "autoapi"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.pypi-dependencies]
mpl-uncertainties = { path = ".", editable = true }

[tool.pixi.tasks]

<<<<<<< HEAD
[tool.pixi.feature.test.tasks]
=======
[tool.pixi.feature.tests.tasks]
>>>>>>> b940ecdd7d807568b9c63eb8bb43c624380dec96
test = "pytest --mpl --mpl-baseline-path=baseline"
test_mpl_generate = "pytest --mpl-generate-path=baseline"

[tool.pixi.environments]
default = { solve-group = "default" }
<<<<<<< HEAD
test = { features = ["test"], solve-group = "default" }
=======
tests = { features = ["tests"], solve-group = "default" }
>>>>>>> b940ecdd7d807568b9c63eb8bb43c624380dec96
docs = { features = ["docs"], solve-group = "default" }
lint = { features = ["lint"], solve-group = "default" }

[tool.pixi.feature.docs.tasks]
<<<<<<< HEAD
build-doc = { cmd = "make html > .log", cwd = "docs" }
=======
build-doc = { cmd = "make html", cwd = "docs" }
>>>>>>> b940ecdd7d807568b9c63eb8bb43c624380dec96
clean-doc = { cmd = "rm -rf _build", cwd = "docs" }
example = { cmd = "python examples/errorbar.py" }

# doc gets used by readthedocs, docs is used by pixi
<<<<<<< HEAD
[project.optional-dependencies]
doc = ["sphinx", "sphinx_copybutton", "sphinx_gallery", "numpydoc", "autoapi"]
=======
# test gets used by pip/github actions, tests is used by pixi
[project.optional-dependencies]
doc = ["sphinx", "sphinx_copybutton", "sphinx_gallery", "numpydoc", "autoapi"]
test = ["pytest", "pytest-mpl"]
>>>>>>> b940ecdd7d807568b9c63eb8bb43c624380dec96

[tool.pixi.feature.lint.dependencies]
pre-commit = "*"
pre-commit-hooks = "*"
taplo = "*"
ruff = "*"
mdformat = "*"
mdformat-ruff = "*"

[tool.pixi.feature.lint.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run --all-files"
